plugins = []
headers = []
redirects = []

[build]
edge_functions = "C:\\Users\\xly\\.zcode\\workspace\\default\\muse-egress-netlify\\netlify\\edge-functions"
publish = "C:\\Users\\xly\\.zcode\\workspace\\default\\muse-egress-netlify\\public"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]